---
version: '0.1'
effect_finders:
  ctl_based:
    formulae:
      - name: TankNotDamagedAfterPumpStarted
        translation: Tank damaged after the pump started
        severity: 10
        detection: 2

      - name: TankNotDamaged
        translation: Tank damaged
        severity: 10
        detection: 2

  state_based:
    components:
      - component_class: control_circuit.PressureSwitch
        state_patterns:
          - translation: Pressure switch detects pressure
            states:
              - state: isPressurized
                is: [True]
          - translation: Pressure switch detects no pressure
            states:
              - state: isPressurized
                is: [False]
      - component_class: control_circuit.Relay
        state_patterns:
          - translation: Relay is powered
            states:
                - state: isPowered
                  is: [True]
          - translation: Relay is not powered
            states:
                - state: isPowered
                  is: [False]
          - translation: Relay contacts closed
            states:
                - state: isConnected
                  is: [True]
          - translation: Relay contacts open
            states:
                - state: isConnected
                  is: [False]
      - component_class: control_circuit.Switch
        state_patterns:
          - translation: Switch is powered
            states:
              - state: isPowered
                is: [True]
          - translation: Switch is not powered
            states:
              - state: isPowered
                is: [False]
          - translation: Switch is actuated
            states:
              - state: isActuated
                is: [True]
          - translation: Switch is not actuated
            states:
              - state: isActuated
                is: [False]
      - component_class: control_circuit.TimerRelay
        state_patterns:
          - translation: Timer relay is powered
            states:
              - state: isPowered
                is: [True]
          - translation: Timer relay is not powered
            states:
              - state: isPowered
                is: [False]
          - translation: Timer relay contacts open
            states:
                - state: isConnected
                  is: [False]
          - translation: Timer relay contacts closed
            states:
                - state: isConnected
                  is: [True]
      - component_class: motor_circuit.Fuse
        state_patterns:
          - translation: Fuse is powered
            states:
              - state: isPowered
                is: [True]
          - translation: Fuse is not powered
            states:
              - state: isPowered
                is: [False]
      - component_class: motor_circuit.Motor
        state_patterns:
          - translation: Fuse is powered
            states:
              - state: isPowered
                is: [True]
          - translation: Fuse is not powered
            states:
              - state: isPowered
                is: [False]
      - component_class: valve_system.Pump
        state_patterns:
          - translation: Pump receives mechanical power
            states:
              - state: isPowered
                is: [True]
          - translation: Pump receives no mechanical power
            states:
              - state: isPowered
                is: [False]
      - component_class: valve_system.PressureTank
        state_patterns:
          - translation: Pressure tank receives pressure
            states:
              - state: isReceivingPressure
                is: [True]
          - translation: Pressure tank receives no pressure
            states:
              - state: isReceivingPressure
                is: [False]
          - translation: Pressure tank is not pressured
            states:
              - state: status
                is: [Unpressured]
          - translation: Pressure tank is pressured
            states:
              - state: status
                is: [Pressurized]
          - translation: Pressure tank is damaged
            states:
              - state: status
                is: [Damaged]

levels:
    probability:
        - number: 1
          upper_limit: 1e-8
        - number: 2
          lower_limit: 1e-8
          upper_limit: 1e-7
        - number: 3
          lower_limit: 1e-7
          upper_limit: 1e-6
        - number: 4
          lower_limit: 1e-6
          upper_limit: 1e-5
        - number: 5
          lower_limit: 1e-5
          upper_limit: 1e-4
    detection:
        - number: 1
          lower_limit: 99.8
        - number: 2
          upper_limit: 99.8
          lower_limit: 99.7
        - number: 3
          upper_limit: 99.6
          lower_limit: 99.5
        - number: 4
          upper_limit: 99.5
          lower_limit: 99.4
        - number: 5
          upper_limit: 99.4
          lower_limit: 99.3
