---
version: '0.1'
effect_finders:
  ctl_based:
    formulae:
      - name: TankNotDamagedAfterPumpStarted
        translation: Tank damaged after the pump started
        severity: 10
        detection: 2

      - name: TankNotDamaged
        translation: Tank damaged
        severity: 10
        detection: 2

levels:
    probability:
        - number: 1
          upper_limit: 1e-8
        - number: 2
          lower_limit: 1e-8
          upper_limit: 1e-7
        - number: 3
          lower_limit: 1e-7
          upper_limit: 1e-6
        - number: 4
          lower_limit: 1e-6
          upper_limit: 1e-5
        - number: 5
          lower_limit: 1e-5
          upper_limit: 1e-4
# detection-levels:
#     - number: 1
#       lower_limit: 99.8
#     - number: 2
#       upper_limit: 99.8
#       lower_limit: 99.7
#     - number: 3
#       upper_limit: 99.6
#       lower_limit: 99.5
#     - number: 4
#       upper_limit: 99.5
#       lower_limit: 99.4
#     - number: 5
#       upper_limit: 99.4
#       lower_limit: 99.3
#
# effects:
#   - description: Disconnected
#       states:
#           control_circuit.Relay.isConnected:
#               value: False
#           control_circuit.TimerRelay.isConnected:
#               value: False
#     - description: Tank is damaged
#         states:
#             valve_system.PressureTank.status:
#                 value: Damaged
#     - description: Tank receives pressure
#         states:
#             valve_system.PressureTank.isReceivingPressure
#                 value: True
#     - description: Receives power
#         states:
#             control_circuit.Relay.isPowered:
#                 value: True
#             control_circuit.Switch.isPowered:
#                 value: True
#             motor_circuit.Motor.isPowered:
#                 value: True
#             motor_circuit.Fuse.isPowered:
#                 value: True
#             valve_system.Pump.isPowered:
#                 value: True
#     - description: Is defect
#         states:
#             control_circuit.TimerRelay.failureMode:
#                 value: Defect
#             control_circuit.PressureSwitch.failureMode:
#                 value: Defect
#             control_circuit.Switch.failureMode:
#                 value: Damaged
#             control_cicuit.Relay.failureMode:
#                 value: Jammed
